var quotes = ['tv series where the world is not ending and nobody is either wearing masks or confined in their houses',
	'the ability to maintain a journal',
	'memes about the world ending and sickness being real',
	'exchanging eye contact with someone in a group that confirms you are on the same page',
	'forgiveness',
	'housemates we can watch cook',
	'an useful mind',
	'chance to say things that we did not say before',
	'silly roommates','coasting on a bicycle',
	'sunsets and sunrises',
	'people you spend so much time with that your mannerisms become one',
	'videos of people saving doggies in abandonment',
	'videos of birds being trained',
	'pillows to scream into',
	'that person who tells us that everything will be ok',
	'dreams of kissing',
	'late night conversations on the patio when the temperature outside just hit hoodie weather',
	'bodies','pop punk from the 2000s',
	'questions for each other',
	'doodles by friends',
	'lovebirds cuddling',
	'dancing awkwardly and not caring',
	'humor',
	'hugs',
	'being inside when it is raining',
	'honest thoughtful apologies',
	'little notebooks',
	'cooking with friends',
	'pictures of our childhood',
	'love',
	'other people',
	'crying in the shower',
	'trees',
	'houseplants',
	'friends on videocalls',
	'memes',
	'crayons',
	'the collective euphoria that comes from clapping from the window and hearing others clap',
	'routines',
	'chick flicks',
	'movies with Michael Cera',
	'our favorite song in loop',
	'virtual tours of museums',
	'nicknames for our loved ones',
	'the paws of our pets',
	'dust that swirls in light',
	'the familiar smell of someone you love',
	'dancing in the kitchen',
	'clean white shoes',
	'pajamas',
	'old journals',
	'freshly sharpened pencils',
	'morning coffee',
	'crisp air',
	'dandelions',
	'sleeping babies',
	'weekends',
	'favorite pajamas',
	'indecisiveness between two lovers over which movie to watch',
	'cartoons from the 90s',
	'Christmas ornaments you made in 3rd grade',
	'pretty backroads',
	'speckled sunlight through trees',
	'chamomile tea with honey and lemon for a sore throat or heart',
	'openness to being wrong sometimes',
	'the sound of kids laughing outside',
	'strangers who let you know you dropped your scarf or hat or glove',
	'the phase of infancy and childhood in which one only takes baths',
	'hammocks',
	'the friend you can call crying',
	'friends who help you pack your things into boxes during a hard time',
	'the smell of freshly cut wood',
	'the ache and pride of finally letting go of the thing weighing you down',
	'yellow leaves',
	'back scratches',
	'queers holding hands in public',
	'candles and company when the power goes out',
	'the ability to change our thoughts and perspectives',
	'shared moments with those we’ve known for so long',
	'deciding it is the opportunity for a new beginning',
	'the potential to help others by changing our actions in the smallest ways',
	'the ability to envision and recognize the potential for a better future',
	'the ability take action towards it in the way we interact with the world, and people in our lives, every day from here on out'
		 

]


function newQuote () {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
		document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];

}
